modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/petrolpark/Destroy/issues"
license="All Rights Reserved"

[[mods]]
modId="destroy"
version="${file.jarVersion}"
displayName="Destroy"
#updateJSONURL=""
displayURL="https://www.modrinth.com/mods/destroy"
logoFile="logo.png"
#credits=""
authors="petrolpark"
description='''A destructive chemistry-based add-on to Create.'''

[[dependencies.destroy]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.destroy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.destroy]]
	modId="create"
	mandatory=true
	versionRange="[0.5.1.f,)"
	ordering="AFTER"
	side="BOTH"

